// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO_1UtKhnXtFrmHAasfpFn5iZzxADylCk',
    appId: '1:945052703909:web:fa3344bd95c5dacbb3414c',
    messagingSenderId: '945052703909',
    projectId: 'codiora',
    authDomain: 'codiora.firebaseapp.com',
    storageBucket: 'codiora.firebasestorage.app',
    measurementId: 'G-Q702S9HR80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_bBBigEvWTX2IuzegHLCSgx8zCOm3ofo',
    appId: '1:945052703909:android:566705ab8ff45a24b3414c',
    messagingSenderId: '945052703909',
    projectId: 'codiora',
    storageBucket: 'codiora.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO_1UtKhnXtFrmHAasfpFn5iZzxADylCk',
    appId: '1:945052703909:web:7a7e2921ed578e35b3414c',
    messagingSenderId: '945052703909',
    projectId: 'codiora',
    authDomain: 'codiora.firebaseapp.com',
    storageBucket: 'codiora.firebasestorage.app',
    measurementId: 'G-YQ55Z29Z30',
  );
}
